### ISSUE TITLE
Getting started process errors

### ISSUE THREAD

**Issue by dwootton** [educational-technology-collective/etc_jupyterlab_telemetry_library#1]
Wanting to add this issue here in case someone else is running into the same issue getting this working. 

I kept on running into errors where activations would fail. Debugging the app, it looks like id fields were missing from the etc_jupyterlab_telemetry_library and etc_jupyterlab_notebook_state_provider. 

Adding in these as "sharedPackages" in the package.json (at the top level) solved this for me like: 
` in package.json
{
...
"jupyterlab": {
    "extension": true,
    "outputDir": "jupyter_recorder/labextension",
      "sharedPackages": {
        "@educational-technology-collective/etc_jupyterlab_telemetry_library": {
          "bundled": false,
          "singleton": true,
          "strictVersion": true
        },
        "@educational-technology-collective/etc_jupyterlab_notebook_state_provider": {
          "bundled": false,
          "singleton": true,
          "strictVersion": true
        }
      }
    
  },
...
}
`

**Comment by adpatter** [comment]
@mengyanw @cab938 I would like to bring your attention to this issue if you haven't seen it already - I think we received this shortly after I started my new job.
